blueprint:
  name: Mon Thermostat Hysterisis Pour Poele
  description: Mon Thermostat Hysterisis
  domain: automation
  source_url: https://github.com/geek78/home-assistant/edit/main/mon_thermostat_hysterisis_pour_poele.yaml

  input:
    hyste_up:
      name: Hystérisis Supérieur
      description: Delta supérieur température admis
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1
    hyste_down:
      name: Hystérisis inférieur
      description: Delta inféreur température admis
      selector:
        number:
          min: 0.5
          max: 2
          step: 0.1
    entity_consigne:
      name: Consigne
      description: Champs d'entrée de la température de consigne (number).
      selector:
        entity:
          domain: number
    entity_temp_int:
      name: Température intérieure
      description: Sonde de mesure de la température intérieure (sensor)
      selector:
        entity:
          domain: sensor
          device_class: temperature
    entity_chauffage:
      name: Chauffage
      description: Interrupteur marche / arrêt du chauffage (switch)
      selector:
        entity:
          domain: switch
    entity_etat_poele:
      name: Etat du poele
      description: Sonde de détection de l'arrêt ou la marche du poele
      selector:
        entity:
          domain: sensor


# Récupération des paramètres
variables:
  entity_temp_int: !input entity_temp_int
  hyste_up: !input hyste_up
  hyste_down: !input hyste_down
  entity_etat_poele: !input entity_etat_poele
  entity_consigne: !input entity_consigne
  entity_chauffage: !input entity_chauffage


trigger:
  - platform: time_pattern
    minutes: "/30"
  - platform: state
    entity_id: !input entity_consigne



action:
  - alias: récupération des données
    variables:
      entity_consigne: !input entity_consigne
      consigne: '{{ states(entity_consigne) }}'
      entity_temp_int: !input entity_temp_int
      temp_int: '{{ states(entity_temp_int) }}'
      entity_etat_poele: !input entity_etat_poele
      etat_poele: '{{ states(entity_etat_poele) }}'
      
  - choose:
      - conditions:
          - condition: template
            value_template: '{{temp_int | float(1) > (consigne | float(1) + hyste_up | float(1) ) and etat_poele == "Marche" }}'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input entity_chauffage
      - conditions:
          - condition: template
            value_template: '{{temp_int | float(1) < (consigne | float(1) - hyste_down | float(1)) and etat_poele == "Arrêt" }}'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input entity_chauffage
    default:
      - service: switch.turn_on
        target:
          entity_id: !input entity_chauffage
mode: restart

mode: restart
